# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Profil użytkownika', 'verbose_name_plural': 'Profile użytkowników'},
        ),
    ]
