# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_faq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['timestamp']},
        ),
    ]
