# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20170413_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['timestamp'], 'verbose_name': 'Pytanie i odp.', 'verbose_name_plural': 'Pytania i odpowiedzi'},
        ),
        migrations.AlterModelOptions(
            name='join',
            options={'ordering': ['timestamp'], 'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletter'},
        ),
    ]
