# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170410_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Zdjęcie produktu', 'verbose_name_plural': 'Zdjęcia produktów'},
        ),
    ]
