# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20170414_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wislist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
