# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_wislist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wislist',
            new_name='wishlist',
        ),
    ]
