# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 17:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170503_1728'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
